name: dr_fit
description: "This fitness app is designed as a holistic solution for users seeking to improve their health and fitness. By integrating various features such as personalized plans, community support, and real-time feedback, it empowers users to take control of their fitness journeys in a convenient and engaging way."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  shared_preferences: ^2.3.2
  bloc_provider: ^1.0.0
  flutter_bloc: ^9.1.0
  fluttertoast: ^8.2.12
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  vertical_weight_slider: ^2.6.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  dio: ^5.8.0+1
  loading_animation_widget: ^1.3.0
  conditional_builder_null_safety: ^0.0.6
  google_mlkit_translation: ^0.13.0
  slang_gpt: ^0.11.0
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  uuid: ^4.5.1
  awesome_dialog: ^3.2.1
  translator: ^1.0.3+1
  cached_network_image: ^3.4.1
  chat_bubbles: ^1.7.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
#  flutter_native_splash: ^2.4.2
#  flutter_launcher_icons: ^0.14.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - keys.env



#flutter_native_splash:
#  color: "#EDE9FF"
#  image: "assets/images/splash.png"
#
#flutter_launcher_icons:
#  ios: true
#  android: true
#  image_path_android: "assets/logo/logo.png"
#  image_path_ios: "assets/logo/logo.png"
#  adaptive_icon_foreground: "assets/logo/logo.png"
#  adaptive_icon_background: "assets/logo/logo.png"




  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
